language: php
php:
- 7.1
- 7.2
cache:
  directories:
    - $HOME/.composer/cache
env:
  matrix:
  - PREFER_LOWEST="--prefer-lowest"
  - PREFER_LOWEST=""
before_script:
- composer update --prefer-dist $PREFER_LOWEST
- wget https://github.com/infection/infection/releases/download/0.7.1/infection.phar
- wget https://github.com/infection/infection/releases/download/0.7.1/infection.phar.pubkey
- chmod +x infection.phar
- mkdir -p build/logs
script:
- "./vendor/bin/phpunit"
- ./infection.phar
after_script:
- if [ -z "$PREFER_LOWEST" ]; then ./vendor/bin/coveralls -v; fi
