language: php
php:
- 7.1
- 7.2
cache:
  directories:
    - $HOME/.composer/cache
env:
  matrix:
  - PREFER_LOWEST="--prefer-lowest"
  - PREFER_LOWEST=""
before_script:
- composer update --prefer-dist $PREFER_LOWEST
- git clone https://github.com/padraic/humbug.git && cd humbug && composer install && cd ..
script:
- "./vendor/bin/phpunit"
- ./humbug/bin/humbug
after_script:
- if [ -z "$PREFER_LOWEST" ]; then ./vendor/bin/coveralls -v; fi
